"""
AgentsCourt Judge Analysis Record Module
Generate professional analysis and judgment opinions from court debate records

Main Functions:
1. Read case data and trial records
2. Conduct professional analysis from judge's perspective based on trial debate process
3. Generate judge analysis opinions in judicial format
4. Include judge analysis, trial basis, final judgment in three standardized outputs

Applicable Scenarios:
- Judge analysis for second-instance cases
- Comprehensive judgment based on first-instance facts and trial debates
- Support criminal, civil, administrative cases

Authors: AgentsCourt Team
Date: 2024
"""

# -*- coding: utf-8 -*-
import json
from tqdm import tqdm 
from ollama_utils import ollama_simple_completion
import os

def num_tokens_from_string(string: str, encoding_name: str) -> int:
    """
    Simplified function to estimate text token count
    
    Args:
        string (str): Input text
        encoding_name (str): Encoding name (reserved parameter for compatibility)
        
    Returns:
        int: Estimated token count (simplified to word count)
        
    Note:
        Since using Ollama local model, adopt simplified token calculation method
        In actual application, token estimation strategy can be adjusted according to specific model
    """
    # Since using Ollama, simplify token calculation
    # Token count can be estimated using other methods as needed
    return len(string.split())

def GPT_4(system_massage, prompt):
    """
    Unified interface to call large language model to generate judge analysis
    
    Args:
        system_massage (str): System prompt, defining judge role and behavior norms
        prompt (str): User input prompt, containing case information and trial records
        
    Returns:
        str: Judge analysis result generated by the model
        
    Note:
        Internally uses Ollama API to call qwen3:30b-a3b model
        Keep function name as GPT_4 for compatibility with existing code structure
    """
    return ollama_simple_completion(prompt, system_massage)

def auto_judge(output_path, test_list=[], assigned_dir=None):
    # ===== Data Loading Phase =====
    # 1. Load case basic data
    case_dataset = 'data/criminal_cases.json'
    with open(case_dataset, 'r', encoding='utf-8') as file:
        case_data = json.load(file)

    # 2. Load trial record data (generated by main_court module)
    if assigned_dir is not None:
        output_path = assigned_dir
    else:
        court_record_path = f'{output_path}/court_records.json'
    # For testing - fixed trial record
    with open(court_record_path, 'r', encoding='utf-8') as file:
        court_record = json.load(file)

    # 3. Load judge role system prompt
    judge_analysis_record_path = 'system_prompt/judge_analysis_record.txt'
    with open(judge_analysis_record_path, "r", encoding='utf-8') as f:
        judge_analysis_record_system = f.read()

    # ===== Initialize Result Containers =====
    judge_analysis_record_result = {}  # Store judge analysis results for all cases
    judge_analysis_record_token = {}   # Store token consumption for judge analysis - including thinking process
    error_list = []                   # Record failed case IDs
    error_case_list = []              # Reserved field for expansion

    if len(test_list) > 0:
        case_data = [x for x in case_data if x['案号'] in test_list]


    # ===== Main Processing Loop: Batch Process Cases =====
    for case_test in tqdm(case_data, desc="处理案件进度"):
        # ===== Trial Record Extraction and Validation =====
        try:
            # Check if current case has trial record
            if case_test['案号'] in court_record:
                current_court_record = court_record[case_test['案号']]
                # Merge multi-round trial records into complete text
                if len(current_court_record) >= 2:
                    record1 = current_court_record[0]  # First round speech (usually plaintiff accusation)
                    record2 = current_court_record[1]  # Second round speech (usually defendant defense)
                    current_court_record_text = record1 + "\n" + record2
                else:
                    # Case with only one round of record
                    current_court_record_text = current_court_record[0]
            else:
                # Skip processing for cases without trial records
                raise Exception("庭审记录为空")
        except Exception as e:
            # Record failed case IDs and continue processing next case
            error_list.append(case_test['案号'])
            print(f"案件 {case_test['案号']} 处理失败: {e}")
            continue  # Skip current case, continue processing next
        # ===== Judge Role Prompt Template =====
        # This is the core prompt template, defining judge's behavior norms and output format
        CASE_TEMPLATE_ = """你正在参与一次模拟法庭的活动，请记住这是一场虚拟的过程，你现在扮演一位专业的法官，请根据以下指引进行发言：

        请注意以下几点：
        1、若当前案件为**刑事案件**：则需要首先明确被告人的具体罪名和犯罪事实。评估犯罪行为对受害者及社会造成的影响和危害。考虑被告人的认罪态度、悔罪表现及犯罪后的改正行为。
        2、若当前案件为**民事案件**：则需要确立案件争议焦点，如合同违约、财产纠纷、侵权行为等。根据所提供的证据，评估各方责任大小和责任分配。确定适当的赔偿金额或其他补救措施，如返还财产、停止侵权行为等。
        3、若当前案件为**行政案件**：则需要分析涉案的行政行为是否符合法律法规的要求，是否超越了行政机关的权限。考虑行政行为对个人或组织的影响，是否有侵犯合法权益的情况。在判定行政行为不当或非法时，考虑适当的补救措施，如撤销行政决定、恢复原状、赔偿损失等。

        不管什么情况下，你的每一次发言只能且必须遵守以下格式：
        [法官分析]：本院认为，<你的分析>
        [审判依据]：综上所述，依照：<你依据的法律条文（陈列出案件涉及的法律条款具体名称如第几条第几款第几项）>
        [最终判决]：判决如下：<你的判决（必须给出判决结果，且不可包含除判决结果外的内容）>

        以下是一些案件的基本情况、庭审记录及最终判决结果：
        ###
        原告：江苏省淮安经济技术开发区人民检察院
        被告：范某
        案件类型: 刑事案件
        法院认定事实：2021年11月7日21时5分许，被告人范某醉酒后驾驶苏Ｈ×××**号小型轿车，从本市香溢茗园小区出发，途经水渡口大道、合肥路、深圳路，沿深圳路由西向东行驶至深圳路与宁连路交叉路口西侧50米时，碰撞护栏，造成车辆及护栏损坏的道路交通事故，被巡逻的民警现场查获。经鉴定，被告人范某血液中乙醇含量为210.2mg/100ml。
        庭审辩论：
        [原告控诉]：我作为原告控诉：被告人范某的行为已构成危险驾驶罪，事实清楚，证据确实、充分。指控理由如下：1、2021年11月7日21时许，被告人范某醉酒后驾驶苏H牌照小型轿车上路行驶，并与道路护栏发生碰撞，造成了交通事故。2、经鉴定，其血液内乙醇含量高达210.2mg/100ml，属于醉酒驾驶。3、其行为危及了公共安全，触犯了《中华人民共和国刑法》第一百三十三条之一的规定。被告人醉酒驾驶发生事故，应从重处罚；归案后如实供述，系坦白，可从轻处罚。提请法庭依法判处。
        [被告辩解]：我对公诉机关指控的事实、罪名以及量刑建议全部没有异议，我自愿认罪认罚。事发当晚我确实喝多了酒，侥幸开车，结果出了事故，我现在非常后悔。我的行为给社会带来了安全隐患，我愿意承担一切法律后果。我已经如实向司法机关交代了所有情况，希望法庭能够看在我坦白和真诚悔罪的态度上，对我从轻处理。
        最终裁决：
        [法官分析]：本院认为，被告人范某在道路上醉酒驾驶机动车，发生交通事故，危及公共安全，其行为已构成危险驾驶罪。淮安经济技术开发区人民检察院指控罪名成立，本院予以采纳。被告人范某醉酒驾驶机动车发生交通事故，应当酌情从重处罚；归案后如实供述犯罪事实，系坦白，依法可以从轻处罚。
        [审判依据]：《中华人民共和国刑法》第一百三十三条之一第一款第（二）项，第六十七条第三款
        [最终判决]：被告人范某犯危险驾驶罪，判处拘役二个月，并处罚金人民币二千元。
        
        你将收到当前案件的基本信息、法庭辩论，请根据你作为一名法官的专业知识进行最终的判决。
        不管什么情况，你必须在[最终判决]中给出如示例中的明确的判决结果！
        原告：{case_plaintiff}
        被告：{case_defendant}，被告基本情况：{case_defendant_detail}
        案件类型: {case_type}
        法院认定事实：{case_fact}
        庭审辩论：{court_debate}
            最终裁决："""
        
        # ===== Build Complete Case Analysis Prompt =====
        task_prompt = CASE_TEMPLATE_.format(
            case_plaintiff=case_test["原告（公诉）"],
            case_defendant=case_test["被告"],
            case_defendant_detail=case_test["被告基本情况"],
            case_type=case_test["类别"] + '案件',
            case_fact=case_test["基本案情"],
            court_debate=current_court_record_text  # Use extracted trial records
        )
        
        # ===== Call LLM to Generate Judge Analysis =====
        try:
            # Use large language model to generate judge's professional analysis and judgment
            judge_self_analysis, token = GPT_4(judge_analysis_record_system, task_prompt)
            
            # Save results to dictionary
            judge_analysis_record_result[case_test['案号']] = judge_self_analysis
            
            judge_analysis_record_token[case_test['案号']] = token
            
            # Display generated analysis results in real time
            print(f"\n=== 案件 {case_test['案号']} 法官分析 ===")
            print(judge_self_analysis)
            print("=" * 50)
            
        except Exception as e:
            # Handle LLM call failure situation
            print(f'生成法官分析时发生错误: {case_test["案号"]} - {e}')
            error_list.append(case_test['案号'])

        # ===== Save Results in Real Time =====
        # Save after processing each case to prevent data loss from program interruption
        if len(test_list) != 0:
            with open(f'{output_path}/record.json', 'r', encoding='utf-8') as file:
                r = json.load(file)
            with open(f'{output_path}/record_token.json', 'r', encoding='utf-8') as file:
                rt = json.load(file)
                
            for r_id in judge_analysis_record_result:
                r[r_id] = judge_analysis_record_result[r_id]
                rt[r_id] = judge_analysis_record_token[r_id]
            with open(f'{output_path}/record.json', 'w', encoding='utf-8') as file:
                json.dump(r, file, ensure_ascii=False, indent=4)
            with open(f'{output_path}/record_token.json', 'w', encoding='utf-8') as file:
                json.dump(rt, file, ensure_ascii=False, indent=4)
        else:
            with open(f'{output_path}/record.json', 'w', encoding='utf-8') as file:
                json.dump(judge_analysis_record_result, file, ensure_ascii=False, indent=4)
            with open(f'{output_path}/record_token.json', 'w', encoding='utf-8') as file:
                json.dump(judge_analysis_record_token, file, ensure_ascii=False, indent=4)
    # ===== Statistical Information After Processing Completion =====
    print(f"\n处理完成！")
    print(f"成功处理案件数: {len(judge_analysis_record_result)}")
    print(f"失败案件数: {len(error_list)}")
    if error_list:
        print(f"失败的案件ID: {error_list}")
    else:
        print("所有案件都处理成功！")


if __name__ == "__main__":
    # ===== Data Loading Phase =====
    # 1. Load case basic data
    case_dataset = 'data/criminal_cases.json'
    with open(case_dataset, 'r', encoding='utf-8') as file:
        case_data = json.load(file)

    # 2. Load trial record data (generated by main_court module)
    court_record_path = "results/4-rounds-qwen3-30b/retest-2/court_records.json"
    current_directory = os.path.dirname(court_record_path)

    with open(court_record_path, 'r', encoding='utf-8') as file:
        court_record = json.load(file)

    # 3. Load judge role system prompt
    judge_analysis_record_path = 'system_prompt/judge_analysis_record.txt'
    with open(judge_analysis_record_path, "r", encoding='utf-8') as f:
        judge_analysis_record_system = f.read()

    # ===== Initialize Result Containers =====
    judge_analysis_record_result = {}  # Store judge analysis results for all cases
    judge_analysis_record_token = {}   # Store token consumption for judge analysis - including thinking process
    error_list = []                   # Record failed case IDs
    error_case_list = []              # Reserved field for expansion

    test_list = []  # Supplementary cases

    if len(test_list) > 0:
        case_data = [x for x in case_data if x['案号'] in test_list]

    # ===== Main Processing Loop: Batch Process Cases =====
    for case_test in tqdm(case_data, desc="处理案件进度"):
        # ===== Trial Record Extraction and Validation =====
        try:
            # Check if the current case has court records
            if case_test['案号'] in court_record:
                current_court_record = court_record[case_test['案号']]

                # 合并多轮庭审记录为完整文本
                if len(current_court_record) >= 2:
                    record1 = current_court_record[0]  # 第一轮发言（通常是原告控诉）
                    record2 = current_court_record[1]  # 第二轮发言（通常是被告辩解）
                    current_court_record_text = record1 + "\n" + record2
                else:
                    # 只有一轮记录的情况
                    current_court_record_text = current_court_record[0]
            else:
                # 没有庭审记录的案件跳过处理
                raise Exception("庭审记录为空")

        except Exception as e:
            # 记录处理失败的案件ID，并继续处理下一个案件
            error_list.append(case_test['案号'])
            print(f"案件 {case_test['案号']} 处理失败: {e}")
            continue  # 跳过当前案件，继续处理下一个

        # ===== 法官角色提示词模板 =====
        # 这是核心的提示词模板，定义法官的行为规范和输出格式
        CASE_TEMPLATE_ = """你正在参与一次模拟法庭的活动，请记住这是一场虚拟的过程，你现在扮演一位专业的法官，请根据以下指引进行发言：

            请注意以下几点：
            1、若当前案件为**刑事案件**：则需要首先明确被告人的具体罪名和犯罪事实。评估犯罪行为对受害者及社会造成的影响和危害。考虑被告人的认罪态度、悔罪表现及犯罪后的改正行为。
            2、若当前案件为**民事案件**：则需要确立案件争议焦点，如合同违约、财产纠纷、侵权行为等。根据所提供的证据，评估各方责任大小和责任分配。确定适当的赔偿金额或其他补救措施，如返还财产、停止侵权行为等。
            3、若当前案件为**行政案件**：则需要分析涉案的行政行为是否符合法律法规的要求，是否超越了行政机关的权限。考虑行政行为对个人或组织的影响，是否有侵犯合法权益的情况。在判定行政行为不当或非法时，考虑适当的补救措施，如撤销行政决定、恢复原状、赔偿损失等。

            不管什么情况下，你的每一次发言只能且必须遵守以下格式：
            [法官分析]：本院认为，<你的分析>
            [审判依据]：综上所述，依照：<你依据的法律条文（陈列出案件涉及的法律条款具体名称如第几条第几款第几项）>
            [最终判决]：判决如下：<你的判决（必须给出判决结果，且不可包含除判决结果外的内容）>

            以下是一些案件的基本情况、庭审记录及最终判决结果：
            ###
            原告：江苏省淮安经济技术开发区人民检察院
            被告：范某
            案件类型: 刑事案件
            法院认定事实：2021年11月7日21时5分许，被告人范某醉酒后驾驶苏Ｈ×××**号小型轿车，从本市香溢茗园小区出发，途经水渡口大道、合肥路、深圳路，沿深圳路由西向东行驶至深圳路与宁连路交叉路口西侧50米时，碰撞护栏，造成车辆及护栏损坏的道路交通事故，被巡逻的民警现场查获。经鉴定，被告人范某血液中乙醇含量为210.2mg/100ml。
            庭审辩论：
            [原告控诉]：我作为原告控诉：被告人范某的行为已构成危险驾驶罪，事实清楚，证据确实、充分。指控理由如下：1、2021年11月7日21时许，被告人范某醉酒后驾驶苏H牌照小型轿车上路行驶，并与道路护栏发生碰撞，造成了交通事故。2、经鉴定，其血液内乙醇含量高达210.2mg/100ml，属于醉酒驾驶。3、其行为危及了公共安全，触犯了《中华人民共和国刑法》第一百三十三条之一的规定。被告人醉酒驾驶发生事故，应从重处罚；归案后如实供述，系坦白，可从轻处罚。提请法庭依法判处。
            [被告辩解]：我对公诉机关指控的事实、罪名以及量刑建议全部没有异议，我自愿认罪认罚。事发当晚我确实喝多了酒，侥幸开车，结果出了事故，我现在非常后悔。我的行为给社会带来了安全隐患，我愿意承担一切法律后果。我已经如实向司法机关交代了所有情况，希望法庭能够看在我坦白和真诚悔罪的态度上，对我从轻处理。
            最终裁决：
            [法官分析]：本院认为，被告人范某在道路上醉酒驾驶机动车，发生交通事故，危及公共安全，其行为已构成危险驾驶罪。淮安经济技术开发区人民检察院指控罪名成立，本院予以采纳。被告人范某醉酒驾驶机动车发生交通事故，应当酌情从重处罚；归案后如实供述犯罪事实，系坦白，依法可以从轻处罚。
            [审判依据]：《中华人民共和国刑法》第一百三十三条之一第一款第（二）项，第六十七条第三款
            [最终判决]：被告人范某犯危险驾驶罪，判处拘役二个月，并处罚金人民币二千元。
            
            你将收到当前案件的基本信息、法庭辩论，请根据你作为一名法官的专业知识进行最终的判决。
            不管什么情况，你必须在[最终判决]中给出如示例中的明确的判决结果！
            原告：{case_plaintiff}
            被告：{case_defendant}，被告基本情况：{case_defendant_detail}
            案件类型: {case_type}
            法院认定事实：{case_fact}
            庭审辩论：{court_debate}
            最终裁决："""
        # 处于 最终裁决： 上一行

        # ===== 构建完整的案件分析提示词 =====
        task_prompt = CASE_TEMPLATE_.format(
                case_plaintiff=case_test["原告（公诉）"], 
                case_defendant=case_test["被告"],
                case_defendant_detail=case_test["被告基本情况"],
                case_type=case_test["类别"] + '案件',
                case_fact=case_test["基本案情"],
                court_debate=current_court_record_text  # 使用提取的庭审记录
            )

        # ===== 调用LLM生成法官分析 =====
        try:
            # 使用大语言模型生成法官的专业分析和判决
            judge_self_analysis, token = GPT_4(judge_analysis_record_system, task_prompt)

            # 保存结果到字典中
            judge_analysis_record_result[case_test['案号']] = judge_self_analysis

            judge_analysis_record_token[case_test['案号']] = token

            # 实时显示生成的分析结果
            print(f"\n=== 案件 {case_test['案号']} 法官分析 ===")
            print(judge_self_analysis)
            print("=" * 50)

        except Exception as e:
            # 处理LLM调用失败的情况
            print(f'生成法官分析时发生错误: {case_test["案号"]} - {e}')
            error_list.append(case_test['案号'])

        # ===== 实时保存结果 =====
        # 每处理一个案件就保存一次，防止程序中断导致数据丢失
        if len(test_list) != 0:
            with open(f'{current_directory}/record.json', 'r', encoding='utf-8') as file:
                r = json.load(file)
            with open(
                f"{current_directory}/record_token.json",
                "r",
                encoding="utf-8",
            ) as file:
                rt = json.load(file)
            for r_id in judge_analysis_record_result:
                r[r_id] = judge_analysis_record_result[r_id]
                rt[r_id] = judge_analysis_record_token[r_id]
            with open(
                f"{current_directory}/record.json",
                "w",
                encoding="utf-8",
            ) as file:
                json.dump(r, file, ensure_ascii=False, indent=4)
            with open(
                f"{current_directory}/record_token.json",
                "w",
                encoding="utf-8",
            ) as file:
                json.dump(rt, file, ensure_ascii=False, indent=4)
        else:
            with open(
                f"{current_directory}/record.json",
                "w",
                encoding="utf-8",
            ) as file:
                json.dump(judge_analysis_record_result, file, ensure_ascii=False, indent=4)
            with open(
                f"{current_directory}/record_token.json",
                "w",
                encoding="utf-8",
            ) as file:
                json.dump(judge_analysis_record_token, file, ensure_ascii=False, indent=4)
    # ===== 处理完成后的统计信息 =====
    print(f"\n处理完成！")
    print(f"成功处理案件数: {len(judge_analysis_record_result)}")
    print(f"失败案件数: {len(error_list)}")
    if error_list:
        print(f"失败的案件ID: {error_list}")
    else:
        print("所有案件都处理成功！")
